- name: Start Proxmox Machine
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "10.1.100.100"
    proxmox_user: "root@pam"
    proxmox_token_name: "ansible"
    node: "deployone"

  tasks:
    - name: Load secrets file
      include_vars:
        file: vars/secrets.yml

    - name: Start machine (LXC)
      community.proxmox.proxmox:
        vmid: "{{ vmid }}"
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_name }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        validate_certs: false
        state: started
      ignore_errors: true # In case it's actually a VM, we try both

    - name: Start machine (VM/QEMU)
      community.proxmox.proxmox_kvm:
        vmid: "{{ vmid }}"
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_name }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        validate_certs: false
        state: started
      ignore_errors: true
