- name: Install nginx
  hosts: test
  remote_user: root

  tasks:
    - name: Installing nginx
      package:
        name: nginx
        state: present

    - name: Ensure it's started and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Delete default nginx html
      file:
        path: /var/www/html/index*.html
        state: absent

    - name: Send html file
      template:
        src: ./index.html
        dest: /var/www/html/index.html