---
- name: Instalar y configurar servidor DNS
  hosts: dns
  become: yes

  vars:
    dns_forwarders:
      - 8.8.8.8
      - 8.8.4.4

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar Bind9 y utilidades
      apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
          - dnsutils
        state: present

    - name: Configurar named.conf.options
      copy:
        dest: /etc/bind/named.conf.options
        content: |
          options {
            directory "/var/cache/bind";

            recursion yes;
            allow-query { any; };
            listen-on { any; };
            allow-recursion { any; };

            forwarders {
              {% for ip in dns_forwarders %}
              {{ ip }};
              {% endfor %}
            };

            dnssec-validation auto;
            auth-nxdomain no;
          };

    - name: Habilitar y reiniciar Bind9
      service:
        name: bind9
        enabled: yes
        state: restarted
